// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqiR2j6SMVXku0ZhjdlEp-GFCpSE0BcxU',
    appId: '1:256432095296:web:6b1c1bfa657600a7bcdfa5',
    messagingSenderId: '256432095296',
    projectId: 'mobileapp-31b5c',
    authDomain: 'mobileapp-31b5c.firebaseapp.com',
    storageBucket: 'mobileapp-31b5c.firebasestorage.app',
    measurementId: 'G-N1T1KJ115M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhlwC1d6qnqVceAiPZZAXdYUvRWv6LIPI',
    appId: '1:256432095296:android:fefbac8d93b5de2abcdfa5',
    messagingSenderId: '256432095296',
    projectId: 'mobileapp-31b5c',
    storageBucket: 'mobileapp-31b5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1OMdjNYANKicoB_vCf7q9kIblLn16tXI',
    appId: '1:256432095296:ios:bbc3c5c755aceadebcdfa5',
    messagingSenderId: '256432095296',
    projectId: 'mobileapp-31b5c',
    storageBucket: 'mobileapp-31b5c.firebasestorage.app',
    iosBundleId: 'com.example.eventProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1OMdjNYANKicoB_vCf7q9kIblLn16tXI',
    appId: '1:256432095296:ios:bbc3c5c755aceadebcdfa5',
    messagingSenderId: '256432095296',
    projectId: 'mobileapp-31b5c',
    storageBucket: 'mobileapp-31b5c.firebasestorage.app',
    iosBundleId: 'com.example.eventProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqiR2j6SMVXku0ZhjdlEp-GFCpSE0BcxU',
    appId: '1:256432095296:web:3be529b00ef56d0fbcdfa5',
    messagingSenderId: '256432095296',
    projectId: 'mobileapp-31b5c',
    authDomain: 'mobileapp-31b5c.firebaseapp.com',
    storageBucket: 'mobileapp-31b5c.firebasestorage.app',
    measurementId: 'G-P9KF6JG0P7',
  );
}
